Create AppFunctions.md
sahlet-official/sleeplog pull request #41
Opened 2022-12-04 14:28 UTC by naila135

Resolve #31

2022-12-05 10:38 UTC, sahlet-official requested changes

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +This is a list of features that the application will receive in the MVP version.<br>
Change "receive" -> "give the user"

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +- the application records the nature of sleep without trackers;
change line to
the application superficially records sleep variability without external tracker devices;

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +- the user can refine and / or change additional data applications;
Change please to
the user can edit and supplement sleep data records;

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +- the user can add notes to each dream and thus keep a journal;
Change please to
the user can add comments to each sleep record;

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +- the application visualizes the received data in the form of graphs;
the application visualizes the data series in the form of different types of graphs;

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +- analysis data can be viewed in the form of a log;
Change please to
stored sleep records can be viewed in the form of a log;

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +- complete the sleep log;
Change please to
edit/fill and confirm the sleep record;

2022-12-05 10:38 UTC, sahlet-official commented on Specification/UserFlow/AppFunctions.md
> +- edit sleep data;
Remove line please

2022-12-06 15:56 UTC, naila135 commented on Specification/UserFlow/AppFunctions.md
> +This is a list of features that the application will receive in the MVP version.<br>
done, but changed a little to make it grammaticaly correct

2022-12-06 15:56 UTC, naila135 commented on Specification/UserFlow/AppFunctions.md
> +- the application records the nature of sleep without trackers;
done

2022-12-06 15:57 UTC, naila135 commented on Specification/UserFlow/AppFunctions.md
> +- the user can refine and / or change additional data applications;
done

2022-12-06 15:57 UTC, naila135 commented on Specification/UserFlow/AppFunctions.md
> +- the user can add notes to each dream and thus keep a journal;
done

2022-12-06 15:58 UTC, naila135 commented on Specification/UserFlow/AppFunctions.md
> +- the application visualizes the received data in the form of graphs;
done

2022-12-06 16:01 UTC, naila135 commented on Specification/UserFlow/AppFunctions.md
> +- edit sleep data;
done

2022-12-06 16:01 UTC, sahlet-official approved these changes

2022-12-06 17:47 UTC, merged