Sleeplog UI mockup
sahlet-official/sleeplog pull request #45
Opened 2022-12-10 13:09 UTC by Yura-0

2023-01-02 10:41 UTC, sahlet-official requested changes

2023-01-02 10:41 UTC, sahlet-official commented on Sources/UiMockup/sleeplog_flutter_app/lib/colors.dart
> +class ColorsNames{
Good irea to make devidid class!!!

Rename to Colors

2023-01-02 10:41 UTC, sahlet-official commented on Sources/UiMockup/sleeplog_flutter_app/lib/home_screen.dart
> +
Remove redundant empty lines in all project (not only here)

2023-01-02 10:41 UTC, sahlet-official commented on Sources/UiMockup/sleeplog_flutter_app/lib/home_screen.dart
> +                              fontFamily: "Monsserat",
Do the same thing for fonts - make a divided class with constants.

And make there like

fontName1 = ....
fontName2 = ....

defaultFont = fontName1
defaultFontSize = ...
bigFont = ...
bigFontSize = fontName2

2023-01-02 10:41 UTC, sahlet-official commented on Sources/UiMockup/sleeplog_flutter_app/lib/assets.dart
> +class Assets{
Use the default dart code style here.
ClassName { ...

2023-01-02 10:41 UTC, sahlet-official commented on Sources/UiMockup/sleeplog_flutter_app/lib/navigation_bar.dart
> +}
Make new line in the end of file (in whole project)

2023-01-02 10:41 UTC, sahlet-official commented on Sources/UiMockup/sleeplog_flutter_app/lib/main.dart
> +class MyApp extends StatelessWidget {
Rename MyApp to SleeplogApp

2023-01-02 11:20 UTC, Yura-0 commented on Sources/UiMockup/sleeplog_flutter_app/lib/colors.dart
> +class ColorsNames{
Class Colors is the standard flutter class name. I can't name my custom class "Colors"

2023-01-12 18:58 UTC, Yura-0 commented on Sources/UiMockup/sleeplog_flutter_app/lib/navigation_bar.dart
> +}
I can't fix it, because in the project I have these empty lines, but on GitHub, they are not visible. I tried to make only this change, but the GitHub desktop would not let me commit them because I did not see them

2023-01-23 19:50 UTC, sahlet-official approved these changes
Very beautiful code, just a feast for the eyes!
I like him.

2023-01-24 12:28 UTC, merged