Reolve #32
sahlet-official/sleeplog pull request #51
Opened 2022-12-27 16:06 UTC by naila135

Reolve #32

2022-12-27 16:23 UTC, sahlet-official requested changes

2022-12-27 16:23 UTC, sahlet-official commented on Specification/UserFlow/Iterations/Iteration_1.md
> +This is first iteration of UserFlow for Sleeplog.<br>
Well done!

2022-12-27 16:23 UTC, sahlet-official commented on Specification/UserFlow/Iterations/Iteration_1.md
> +Userflow was created based on:
Change whole text to:

This is iteration 1 of UserFlow for Sleeplog.< br>
Userflow was created based on:
- the interview with the Product Owner;
- Product Owner requirements that were conducted from text dialog;
- [app functions] (./../AppFunctions.md);

Userflow was created in [Miro] (https://miro.com/) and can be seen [here] (https://miro.com/app/board/uXjVP9crbcw=/).

________________________

and remove spaces that I did in the links

![image](https://user-images.githubusercontent.com/45210795/209693321-64c76e80-33bd-4f3a-929d-b4e3267117c8.png)

2022-12-27 16:23 UTC, sahlet-official commented on Specification/UserFlow/Iterations/Iteration_1.md
> +This is first iteration of UserFlow for Sleeplog.<br>
Rename doc, please to

Iteration1.md

2022-12-28 00:34 UTC, naila135 commented on Specification/UserFlow/Iterations/Iteration_1.md
> +Userflow was created based on:
![image](https://user-images.githubusercontent.com/82474250/209739631-7c27faae-bbd1-4a7e-8b00-4e6685828180.png)
It looks weird a little

2022-12-28 00:35 UTC, naila135 commented on Specification/UserFlow/Iterations/Iteration_1.md
> +This is first iteration of UserFlow for Sleeplog.<br>
done

2022-12-28 16:23 UTC, sahlet-official reviewed
Rename PR please to

Userflow in miro Iteration1

2022-12-28 16:23 UTC, sahlet-official requested changes
Rename PR please to

Userflow in miro Iteration1

2022-12-28 16:26 UTC, sahlet-official approved these changes

2022-12-28 16:27 UTC, merged