Freedom Toys iteration 1
sahlet-official/sleeplog pull request #65
Opened 2023-03-13 21:25 UTC by naila135

Resolve #40

2023-03-14 11:28 UTC, sahlet-official requested changes

2023-03-14 11:28 UTC, sahlet-official commented on PublisherBrand/Iterations/Iteration1.md
> +- the logo must have a symbolic meaning.<br>
change dot "." to ";"
please

2023-03-14 11:28 UTC, sahlet-official commented on PublisherBrand/Iterations/Iteration1.md
> +- experimental designs.<br>
change dot "." to ";"
please

2023-03-14 11:28 UTC, sahlet-official commented on PublisherBrand/Iterations/Iteration1.md
> +- designs which were proposed by me;<br>
change "me" to "Designer"
please

2023-03-14 11:28 UTC, sahlet-official commented on PublisherBrand/Iterations/Iteration1.md
> +Design was made using Figma and can be seen [here](https://www.figma.com/file/ciA7yOiSqzYXabkYPZtjjy/FreedomToys?node-id=1%3A16&t=oA6l1WjzrlSPPJYq-1)
Put links to all sheets. cant see other sheets

2023-03-14 15:10 UTC, naila135 commented on PublisherBrand/Iterations/Iteration1.md
> +- designs which were proposed by me;<br>
Yep, changed

2023-03-14 15:10 UTC, naila135 commented on PublisherBrand/Iterations/Iteration1.md
> +- the logo must have a symbolic meaning.<br>
Done

2023-03-15 10:31 UTC, sahlet-official approved these changes

2023-03-15 22:32 UTC, merged